[package]
name = "geop-cad-base"
version.workspace = true
edition.workspace = true

[dependencies]
geop-core-math.workspace = true
geop-core-topology.workspace = true
geop-core-sketch.workspace = true
geop-ops.workspace = true
geop-ops-sketch.workspace = true
geop-ops-datums.workspace = true
geop-ops-extrude-revolve.workspace = true
geop-ops-booleans.workspace = true
geop-ops-edit.workspace = true
geop-ops-fillet.workspace = true
geop-ops-assembly.workspace = true
geop-ops-shell.workspace = true
geop-ops-rasterize.workspace = true
geop-ops-subd.workspace = true
geop-ops-sheetmetal.workspace = true
geop-ops-sketch3d.workspace = true
geop-ops-pattern.workspace = true
geop-ops-plastic.workspace = true
geop-ops-harness.workspace = true
geop-ops-surface.workspace = true
serde.workspace = true
serde_json.workspace = true
geop-ops-hole.workspace = true

[dev-dependencies]
geop-ops-extrude-revolve = { workspace = true, features = ["test-shapes"] }
geop-core-geometry.workspace = true
