pub mod argument_validation;
pub mod body;
pub mod boundary;
pub mod build;
pub mod coedge;
pub mod contains;
pub mod distance;
pub mod edge;
pub mod edit;
pub mod euler;
pub mod face;
pub mod ids;
pub mod loop_sampling;
pub mod mass;
pub mod model;
pub mod shell;
pub mod solid;
#[cfg(test)]
pub(crate) mod test_fixtures;
pub mod validation;
pub mod vertex;
pub mod wire;

pub use body::Body;
pub use coedge::{Coedge, CoedgeGeometry, Sense};
pub use edge::Edge;
pub use face::Face;
pub use ids::{CoedgeId, EdgeId, FaceId, ShellId, SolidId, VertexId, WireId};
pub use model::{Curve2, Curve3, Model};
pub use shell::Shell;
pub use solid::Solid;
pub use vertex::Vertex;
pub use wire::Wire;
