[package]
name = "geop-ops-pattern"
version.workspace = true
edition.workspace = true

[dependencies]
geop-core-math.workspace = true
geop-core-geometry.workspace = true
geop-core-topology.workspace = true
geop-ops.workspace = true
geop-ops-booleans.workspace = true
serde.workspace = true

[dev-dependencies]
geop-ops-extrude-revolve = { workspace = true, features = ["test-shapes"] }
geop-ops-rasterize.workspace = true
