[package]
name = "geop-ops-edit"
version.workspace = true
edition.workspace = true

[dependencies]
geop-core-math.workspace = true
geop-core-topology.workspace = true
geop-ops.workspace = true
geop-ops-booleans.workspace = true
geop-ops-extrude-revolve.workspace = true
serde.workspace = true

[dev-dependencies]
geop-ops-extrude-revolve = { workspace = true, features = ["test-shapes"] }
