[package]
name = "geop-ops"
version.workspace = true
edition.workspace = true

[dependencies]
geop-core-math.workspace = true
geop-core-geometry.workspace = true
geop-core-topology.workspace = true
geop-core-sketch.workspace = true
geop-core-solve.workspace = true
geop-ops-derive.workspace = true
geop-ops-rasterize.workspace = true
serde.workspace = true
serde_json.workspace = true
