[package]
name = "geop-ops-sketch"
version.workspace = true
edition.workspace = true

[dependencies]
geop-core-geometry.workspace = true
geop-core-math.workspace = true
geop-core-sketch.workspace = true
geop-core-topology.workspace = true
geop-ops.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
