[package]
name = "geop-ops-surface"
version.workspace = true
edition.workspace = true

[dependencies]
geop-core-math.workspace = true
geop-core-geometry.workspace = true
geop-core-topology.workspace = true
geop-ops.workspace = true
geop-ops-booleans.workspace = true
# For its line constructors, `common::{line2, line3}`.
geop-ops-extrude-revolve.workspace = true
geop-ops-shell.workspace = true
serde.workspace = true

[dev-dependencies]
geop-ops-extrude-revolve = { workspace = true, features = ["test-shapes"] }
